### ISSUE TITLE
[Question] How far did you get with ectool?

### ISSUE THREAD

**Issue by tsuckow** [JamesCJ60/Framework-Hub#1]
How much luck did you have with getting ectool to communicate on windows. It looked like you were trying to use a DLL that is not included in the repo nor a nuget package.

My understanding is Framework uses a modified chrome-ec protocol so any library would either need to be modified for Framework or be generic enough to implement the framework specificness in user space.

**Comment by JamesCJ60** [comment]
Hi, that code hasn't been tested on any HW yet.
