### ISSUE TITLE
Crash on boot with win11

### ISSUE THREAD

**Issue by Oganoth** [JamesCJ60/Framework-Hub#2]
When launching  framework.exe it appear for 2 secs then crash immediatly.

**Comment by 8Sydney8** [comment]
This has also been an issue for me

**Comment by JamesCJ60** [comment]
I’m sorry that you have been experiencing this issue. Please make sure all files within the installation folder have not been blocked by Windows. If the issue still persists after that, I will provide a build which will log all issues that crop up when I get some free time.

**Comment by Oganoth** [comment]
i confirm excluding everything in windows defender don't resolve the crash issue

**Comment by JamesCJ60** [comment]
Hi, both. Could you please try this build, which should now display an error message whenever an issue pops up?
https://github.com/JamesCJ60/Framework-Hub/releases/download/0.0.1/Framework.Hub.Debug.zip

**Comment by Oganoth** [comment]
here is the result 
![image](https://github.com/user-attachments/assets/8622e8f7-b101-4fac-93e5-e4eae8e68f7f)

**Comment by JamesCJ60** [comment]
> here is the result ![image](https://private-user-images.githubusercontent.com/172079787/352821344-8622e8f7-b101-4fac-93e5-e4eae8e68f7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxODAyMDMsIm5iZiI6MTcyMjE3OTkwMywicGF0aCI6Ii8xNzIwNzk3ODcvMzUyODIxMzQ0LTg2MjJlOGY3LWIxMDEtNGZhYy05M2U1LWU0ZWFlOGU2OGY3Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOFQxNTE4MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05Y2RmZThmYmEzNzQwZmFhZDkyOWFhMDVhYTZmMjBjMmI4YTAzZGViMmVjZTY0MzMzNTZmNjc2ZWMyNjUwZWMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BqE6ZUrl5lt3b-Sqg1Eng4BK3WJrBSHOlKQGZ8Ae36I)

Okay, thank you for doing that. I believe I have an idea of the issue. Could you please try the new debug build linked below?
https://github.com/JamesCJ60/Framework-Hub/releases/download/0.0.1/Framework.Hub.Debug.2.zip

**Comment by Oganoth** [comment]
Okay now it boot up fine !
